### ISSUE TITLE
Замечания по именованию

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/GameOfLife#10]
- item и element - просто дженерик имена
```
field.forEach((item, i) => 
item.forEach((element, j) =>
```
итерация по двурмерному массиву - не очень простая штука, поэтому тут лучше более осмысленно назвать, типа row и column, иначе легко потеряться, потому что item и element по существу синонимы и смысла особо не несут

- ты уверен, что это DEFAULT_NUMBER_OF_GENERATION, а не что-то другое, судя по этому коду? 
```
  setNumberOfGeneration(value) {
    if (value >= constants.DEFAULT_NUMBER_OF_GENERATION) {
      this.numberOfGeneraton = value;
    } else {
      this.numberOfGeneraton = constants.DEFAULT_NUMBER_OF_GENERATION;
    }
  }
```
тут было бы логичнее увидеть MIN или FIRST number of generation. А вообще, я бы не сказал что в данном случае константа нужна даже вообще, потому что как бы логично и довольно очевидно, что первое поколение - это, блин, 1, а не что-то другое)

- `this.endGameStatus = constants.GAME_IS_RUNNING;` это тогда скорее уж gameStatus, а не endGame.
- опечатка в this.y?
```
   ... 
      this.ySizeOfField = Number(value) + constants.DOUBLE_WIDTH_OF_FIELD_BORDER; // 2
    } else {
      this.y = constants.MIN_SIZE_OF_FIELD_WITH_BORDER; // 3
    }
```
- `const oldY = this.xSizeOfField;` oldX?

**Comment by chmnkh** [comment]
- `const previosCellLifeStatus`
previos => previous

**Comment by Sergio-Ka** [comment]
Исправил.

**Comment by chmnkh** [comment]
в циклах же на втором уровне вложенности `cell`, а не `column`
в остальном норм, но я это ишью оставлю на случай еще подобных замечаний, закрою только в самом конце
