### ISSUE TITLE
Клетки должны менять состояние только по клику на них

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/GameOfLife#11]
1. Изменяем один раз состояние какой-либо клетки
2. Кликаем по wrap__content
3. Видим как клетка на которую кликали в п.1 меняет свое состояние на каждый клик по __content

**Comment by Sergio-Ka** [comment]
Исправил.

**Comment by chmnkh** [comment]
1. Зачем теперь coordinate хранить в инстансе класса? Оно же не используется больше никак.
можно сделать просто:
```
const [i, j] = event.target.getAttribute('data-id').split(' ');
this.publish('cellClick', i, j);
```
2. `event.target.nodeName === 'DIV'`
Во-первых я бы проверки на теги никогда не использовал, потому что это сильно общие проверки. А проверки по классу, например, точно однозначно будут идентифицировать объект, потому что у нас БЭМ. Во-вторых, в твоем случае подобная проверка вообще избыточная и достаточно проверки только на дата-атрибут (тут я мб пропустил что-то, поясни если что). 
3. Небольшой, скорее, вопрос. Не настаиваю на фиксе, если только вдруг ты будешь прямо согласен и не захочешь сам исправить. Тебе не кажется логичнее этот хэндлер клика на field вешать, а не на content?

**Comment by Sergio-Ka** [comment]
1. Исправил.
2. Прав. Исправил. Там была проблема с логикой. Вчера уже глаза замылились. Убрал эту проверку.
3. Согласен, логичнее на филд, но не получается, так как поле пересоздается каждый раз при отрисовке с предварительным удалением. Оно конечно можно логику ввести по перенавешиванию при пересоздании, но мне сдается это глупо и вообще не слишком рационально. Либо не пересоздавать поле, но это тогда надо пересмотреть всю логику отрисовки, которая к слову при довольно варварском на первый взгляд подходе работает быстро. Можно конечно типа буферного массива создать во вьюхе, который будет хранить предыдущее состояние поля, сравнивать, выводить разницу и править конкретные клетки. Но сколько обращений к DOM будет для поля 50*50, если хотя бы половина ячеек поменяется? 1250. Гораздо проще создавать новую таблицу во фрагменте, а потом одним действием его аппендить. ИМХО.

**Comment by chmnkh** [comment]
3. Оставь как есть.
