### ISSUE TITLE
Упростить методы

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/GameOfLife#12]
К этому ишью лучше приступать после фикса предыдущих. 

Некоторые методы (например calculateField в field-changer'e) у тебя просто в экран не вмещаются. Такие портянки довольно сложно читать, разбираться в них и все такое прочее.
Куски таких больших методов лучше вынести в дополнительные методы, например в том же calculateField можно вынести в отдельный метод расчет живых соседей. 

На расчете соседей остановлюсь отдельно, тут несколько важных нюансов:
- можно amountOfNeighborsStatuses назвать как aliveNeighbours, будет проще и лаконичнее, такие длинные имена тоже непросто переваривать.
- хранить amountOfNeighborsStatuses свойством класса не совсем логично, потому что это характеристика отдельно взятой клетки, но никак не класса, который рассчитывает поле. То есть это должно быть просто переменной. Плюс, тебе же будет в коде это удобнее: не придется инициализацию в конструкторе делать и писать постоянно this.
- свести массив к какому-то значению (в данном случае к числу) - это типичная задача для `reduce`. И подобные задачи лучше именно им решать. Поэтому почитай про него еще раз, перепиши в расчете соседей forEach на редьюсы, и мб где-то еще в проекте у тебя что-то такое есть.

Тут еще всякая логика с предыдущими поколениями и sumAllCells, которая возможно поменяется после предыдущих ишью, мешает мне еще примеры привести, но суть ясна, я думаю.

**Comment by Sergio-Ka** [comment]
Упростил. amountOfNeighborsStatuses назвал как aliveNeighbours. Думаю по харнению этого значения лучше все же полем класса, потому что его используют теперь не один метод, а инициализация его в конструкторе и так не пользуется. forEach свел к reduce, хотя сильно сократить метод это не помогло, так как все равно приходится смотреть теперь где находится клетка относительно краев и углов. Остальные замечания тоже вроде бы как все.

**Comment by chmnkh** [comment]
> Думаю по харнению этого значения лучше все же полем класса, потому что его используют теперь не один метод, а инициализация его в конструкторе и так не пользуется. 

Оно у тебя используется строго в том месте где происходит расчет соседей. Ты можешь из метода это значение вернуть и спокойно его точно так же использовать. Количество живых соседей - это характеристика клетки, а не характеристика объекта, который считает поле, вот и все.

**Comment by chmnkh** [comment]
1) Почему recountedField - это свойство класса, я тоже не понял.

2) Когда перед тобой стоит задача вернуть массив такого же размера как другой массив, но с другими значениями - это почти наверняка `map`. Поэтому пересчет поля нужно писать с мапом, а не перебирать `forEach`ем. Это будет естественнее и декларативнее, не придется какие-то массивы создавать и изменять их значения.
```
const recountedField = field.field.map(...);
```

3) 
```
if (field.readCellLifeStatus(i, j) === constants.DEAD_CELL
    && this.aliveNeighbors === constants.MIN_SUM_OF_ALIVE_NEIGHBOURS) {
    this.recountedField[i][j] = constants.ALIVE_CELL;
} else if (field.readCellLifeStatus(i, j) === constants.ALIVE_CELL
...
```
это условия адски плохо читаются. Во-первых, зачем каждый раз `field.readCellLifeStatus(i, j)` вызывать, когда можно один раз это сделать? Во-вторых, второй `else  if` избыточный, потому что он ничего не делает. В-третьих, когда ты видишь, что у тебя условия кучу места на экране занимают (а у тебя это в основном за счет констант), то лучше их выносить в отдельные переменные, это читаемость сильно улучшит, а сейчас там все в куче и приходится напрягаться чтобы прочесть это, хотя без проблем можно проще сделать.
 
4) После непосредственного расчета (т.е. после того, как отработает полностью `map`, про который я выше писал), по идее метод `calculateField` должен закончиться. Потому что свою цель он выполнил. То, что дальше происходит - это обновление состояния филда. Непосредственно к расчету поля оно отношения не имеет и в методе _расчета_ поля быть не должно. 

5) То, как ты с филдом работаешь при обсчете, в принципе странно: ты итерируешься по field.field, т.е. ты знаешь, что работаешь с матрицей клеток, но при этом ты почему-то состояние клетки получаешь через field, а не через клетку напрямую, хотя класс field changer об этом знает, потому что он по этой матрице уже итерируется. Если бы ты писал с типами, у тебя было бы так:
```
interface IField {
  field: Array<Array<Cell>>;
  ...
}

calculateField(field: IField) {
    ...
```
у тебя же написано так, будто ты работаешь с матрицей "неизвестно чего" - это странно.

6) 
```
    if (this.runOnceFlag) {
      this.constructor._addOnceFieldToHistory(field);
      this.runOnceFlag = false;
    }
```
это для того, чтобы первое поколение что ли сохранять? 

7) `countAliveNeighbors` - задача сильно в лоб решена, попробуй как-то оптимальней и элегантней это сделать, это возможно)

**Comment by Sergio-Ka** [comment]
Вроде все поправил.

**Comment by chmnkh** [comment]
1. Статические методы убрать
2. field.field[i] заменить на row
3. Условия для оживления/умирания клеток дальше упростить
4. 
```
    const shouldGameOver = field.fieldHistory.some(field => areFieldsEqual(field, recountedField));
    if (shouldGameOver) {
      field.setGameOver(true);
    }
```
5. field и field различать (fieldMatrix?)
6. ` const recountedField = this._calculateField(field.field);`
7. createField на мап перевести
8. 
```
    this.numberOfGeneraton = constants.INITIAL_NUMBER_OF_GENERATION;
    this.gameOver = false;
    this.fieldHistory = [];
```
вынести в метод
9. `this.field[i][j].setLifeStatus(0);` тут константа а не 0
10. `cropFieldOnXaxis(xSize)` переделывать или нет интерфейс, подумать
11. `enlarge`ы попробовать на редьюсах написать
12. `processEventFromModel(rows, colums,` не используются эти аргументы
13. `this.gameOverStatus = gameOverStatus;` переименовать
14. `this.document = window.document;` убрать
15. `event.target.getAttribute('data-id')` дата аттрибут чуть более явно назвать
16. `this.content = this.element.querySelector('.popup-message__content');` префикс js
17. `this.button.addEventListener('click', () => { this._visibleStatus(false); })` метод сделать
18. `this.button` => closeButton
19. `message(textOfMessage)` => showMessage
20. `this.element.style.display = 'block';` сделать это модификатором
21. `_visibleStatus(status)` переименовать с глаголом; подумтаь о том чтобы разнести это на 2 метода
22. `if (this.table)` явно проверять на null
23. `this.table.setAttribute('class', 'field js-field');` можно сеттить класс сразу методом
24. 
```
  let line;
  let cell;
```
объявлять по месту использования
25. `row.forEach((column, j)` cell а не column
26. 
```
if (column.getLifeStatus() === constants.DEAD_CELL) {
          cell.setAttribute('class', 'field__cell field__cell_dead js-field__cell js-field__cell_dead');
        } else if (column.getLifeStatus() === constants.ALIVE_CELL) {
          cell.setAttribute('class', 'field__cell field__cell_alive js-field__cell js-field__cell_alive');
        }
```
возможно можно на тернарник переписать
27. `+standard-button({text:"закрыть", color:"red", jsClass:" js-popup-message-close"})` убрать микс класса

**Comment by chmnkh** [comment]
```
    this.field = this.field.map((row) => {
      const newCells = Array(rowsToAdd).fill().map(() => new Cell());
      return [...row, ...newCells];
    });
```
