### ISSUE TITLE
Хранить все предыдущие поколения, а не последние два

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/GameOfLife#13]

**Comment by Sergio-Ka** [comment]
Добавил этот функционал, функционал касающийся трех поколений и статусов окончания игры полностью выпилил. Сообщение теперь простое выводится. Впрочем подробное и не требовалось по условиям задания, а по условию игры и вообще никакие сообщения не требуются. Методы так же разбил на более простые по ишью #12 за исключением метода расчета соседей. С помощью reduce хорошо сводить числовые массивы, а у меня массивы объектов. С ходу не получается. Ну по этому ишью я там отпишу еще отдельно в 12.
