### ISSUE TITLE
Обработчики событий вынести в отдельные методы

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/GameOfLife#4]
```
    this.content.addEventListener('click', (event) => { this._cellClick(event); });
    this.heightInput.addEventListener('change', () => { this.publish('changeHightInput', Number(this.heightInput.value)); });
```
должно быть
```
    this.content.addEventListener('click', this.handleContentClick);
    this.heightInput.addEventListener('change', handleHeightInputChange);
```

шаблон именования [тут](https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_8av0m/) посмотри. Не обращай внимания на то, что там про реакт-компоненты написано, суть одна и та же.
Чтобы не терялся контекст, можешь в сторону bind-декораторов посмотреть или в сторону [стрелочных функций](https://babeljs.io/docs/en/babel-plugin-proposal-class-properties)

**Comment by Sergio-Ka** [comment]
Исправил таким образом.

**Comment by chmnkh** [comment]
```
_handleHightInputChange() {
```
`hight` - очепятка)

```
window.addEventListener('load', this._handleCreateUniverseButtonClick.bind(this));
this.buttonCreateUniverse.addEventListener('click', this._handleCreateUniverseButtonClick.bind(this));
```
В данном случае конвенцию по хэндлерам нужно тоже соблюдать. Каждое забивание на конвенции вносит в код дополнительную путаницу, которую можно избежать. Как резолвить подобные случаи (это кстати на риззоме по той же ссылке написано, можешь там еще дополнительно почитать):
```
_createUniverse() {
    this.publish('createUniverse', this.heightInput.value, this.widthInput.value);
}

_handleWindowLoad() {
    this.createUniverse();
}

_handleCreateUniverseButtonClick() {
    this.createUniverse();
}
```

```
this.slider.addEventListener('click', this._handleSliderChange.bind(this));
this.slider.addEventListener('mousemove', this._handleSliderChange.bind(this));
```
тут то же самое

**Comment by Sergio-Ka** [comment]
Исправил.
