### ISSUE TITLE
Убрать комментарии к константам

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/GameOfLife#5]
this.xSizeOfField = constants.MIN_SIZE_OF_FIELD_WITH_BORDER; // 3
this.ySizeOfField = constants.MIN_SIZE_OF_FIELD_WITH_BORDER; // 3

иду в константы, меняю MIN_SIZE_OF_FIELD_WITH_BORDER
теперь мне везде комменты что ли править?

**Comment by Sergio-Ka** [comment]
Убрал.
