### ISSUE TITLE
Преобразование типов

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/GameOfLife#6]
```
 setXSizeOfField(value) {
    if (Number(value) >= constants.MIN_SIZE_OF_FIELD) {
      this.xSizeOfField = Number(value) + constants.DOUBLE_WIDTH_OF_FIELD_BORDER; // 2
```
для чего здесь (и в других подобных местах) явно в Number преобразовывается?

**Comment by Sergio-Ka** [comment]
Потому что размерность поля берется из инпутов, а от туда цифры в виде текста падают через value, в итоге получается не корректная работа с выбрасыванием ошибок либо работает, но поле меняется не на тот шаг, что указан.

**Comment by chmnkh** [comment]
ну то есть у тебя модель здесь на конкретную реализацию вьюхи завязана, так что ли?)
то, как там у тебя вьюха данные отдает знает максимум контроллер, но никак не модель
модель - самостоятельный обособленный модуль, и она тут не подстраиваться под особенности внешнего мира должна, а должна свои условия диктовать (определять интерфейс), а если внешний код как-то с ней работать хочет, ему придется эти условия выполнить

ты когда определяешь интерфейсы модели и вьюхи, забудь о внешнем коде вообще и делай как модели и вьюхе будет удобно, а внешний код пусть долбается
думай о них не как о компонентах чего-то целого, а как об отдельных самостоятельных модулях, и тогда такой проблемы по идее не должно возникать

**Comment by Sergio-Ka** [comment]
Убрал все преобразование в контроллер. А кое где и вообще убрал.
