### ISSUE TITLE
Убрать view-specific информацию из модели

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/GameOfLife#7]
```
this.xSizeOfField = Number(value) + constants.DOUBLE_WIDTH_OF_FIELD_BORDER; // 2
```
```
this.xSizeOfField = constants.MIN_SIZE_OF_FIELD_WITH_BORDER; // 3
```
никакой информации о бордерах или о чем-то подобном в модели быть не может

размер поля с точки зрения модели - это размерность матрицы и ничего больше

**Comment by Sergio-Ka** [comment]
Это не имеет отношение ко view, это представление поля внутри модели - есть поле и есть всегда его обрамляющая рамка (border) с мертвыми ячейками, которые в таком качестве и участвуют при пересчете поля. Для них самих расчет не производится, но при расчете живых соседей их значения берутся в сумму, как следствие алгоритм счета соседей одинаков для всех ячеек и не разделяет от куда ячейка на расчет попадает - из центра поля или с краю. Или вопрос конкретно в названии? Как тогда назвать рамку поля кроме как тем чем она по факту является, то есть рамкой поля?

**Comment by chmnkh** [comment]
вау, вот это неочевидно было)

я пока не совсем понимаю, к чему вообще вся логика с "бордерами" написана
обоснуй зачем это надо, потому что мне кажется что это не только усложнение ненужное, но еще и вообще некорректное поведение, потому что, например, почему когда я делаю поле 5х5, мне рисует поле 7х7, я же хотел 5х5?

**Comment by chmnkh** [comment]
А, ну я кажется понял к чему все это. В принципе делать так, чтобы поле было как бы "бесконечным", т.е. левый край был бы продолжением правого и т.д., не обязательно. Ты можешь оставить текущую логику, но от "бордера" вообще избавиться. Тогда у тебя крайние клетки будут просто на 3 соседа меньше всегда иметь. Зато не будет неочевидностей, про которые я выше писал.

**Comment by Sergio-Ka** [comment]
Исправил, убрав "мертвую" рамку поля и поменяв логику расчета соседей.
