### ISSUE TITLE
Sum of all cells

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/GameOfLife#8]
`constants.DEFAULT_SUM_OF_ALL_CELLS`

Во-первых, это скорее количество живых клеток, а не какая-то сумма клеток. Если ты сейчас начнешь рассматривать живые клетки как 0, а мертвые как 1, то константа DEFAULT_SUM_OF_ALL_CELLS уже смысл свой поменяет, разве нет?
Плюс, опять же, само наличие такой константы - это странно, потому что по факту количество живых клеток зависит от текущего состояния матрицы. В таком случае, дефолтное количество живых клеток должно рассчитываться от дефолтного состояния матрицы, а не быть строго задано. Потому что иначе при смене дефолтного состояния матрицы, тебе параллельно придется менять и дефолтное состояние живых клеток. Мало того что это неудобно, так ты еще и рискуешь тогда получить несоответствие дефолтного состояния матрицы и дефолтного количества живых клеток.

По этой же причине наличие метода `setSumOfAllCells` выглядит странным. Как будто мы можем иметь в филде 100 живых клеток, но вызвать метод со значением 150, и это будет ок.

Резюмируя: это значение четко завязано на состояние филда. Поэтому инициализировать его надо исходя из дефолтного состояния филда. И изменяться оно должно так же при изменении филда (раз уж ты хранишь это полем класса, а не просто считаешь методом по требованию), но никак не сеттится с каким-то произвольным значением.

**Comment by Sergio-Ka** [comment]
Необходимость этого придумалась в рамках небольшой оптимизации (или даже попыток оптимизации). Это значение пользуется для остановки игры по окончании жизни. Раньше просто на каждом шаге количество живых клеток считалось циклическим перебором всего поля в методе _stopGame - каждый раз и тупо. Подумалось, что это излишне, если ты например поле очистил, то это значение должно быть нулю равно и ничего перебирать не нужно. Если изменил одну клетку с мертвой на живую кликом по ней, то тоже ничего перебирать в цикле не надо, а просто добавить единицу к общей сумме (или удалить, если клик привел к обратному). Так же можно докидывать значения или удалять при записи со вспомогательного поля в основное, в зависимости от того, что было сделано и не перебирать отдельно. Это поле класса и инициализируется при создании филда путем вызова метода _sumAllCells - при том делается это не вообще всегда, а только когда это действительно надо. И эти сетМетоды и нужны для того, чтобы менять это поле при изменении состояния филда, происходит это просто в другом методе другого класса модели. Или процессорное время ничто, восприятие программиста все? Любые жертвы во имя красоты кода? Если так, то я понимаю тогда, почему растут дистрибутивы операционок в размерах (и не только) и приложения все более требовательны к железу, а функциональность вроде бы особо не меняется с точки зрения обычного пользователя. Или я не так все понял опять?

**Comment by chmnkh** [comment]
Коммент длинный, но перед тем как что-то думать и отвечать, прочти его весь)

> Раньше просто на каждом шаге количество живых клеток считалось циклическим перебором всего поля в методе _stopGame - каждый раз и тупо.

Циклический перебор _всего_ поля не нужен. Тебе достаточно найти лишь одну живую клетку и все. У массивов есть `some` и `every`. Ты мне можешь сказать, что мы все равно можем обходить большую часть поля, если у нас жизнь где-то в нижнем правом углу находится, а мы обходим слева сверху, например. Но даже если так, я очень сомневаюсь, что обсчет в таком случае займет какое-то неприемлемое время. Потому что, опять же, эту игру до тебя люди делали и подобного рода оптимизацией не занимались) Плюс, я не уверен в принципе, что инкремент/декремент свойства класса на каждом изменении клетки - это более оптимизированный вариант, потому что как каждый из движков оптимизирован на разные операции - это вопрос, который лично я не изучал. Тут не все так очевидно, на самом-то деле.

> И эти сетМетоды и нужны для того, чтобы менять это поле при изменении состояния филда, происходит это просто в другом методе другого класса модели.

В том-то и дело, что изменение подобной характеристики извне не должно поступать. Эта характеристика отражает текущее состояние поля. Ты же, вместо того, чтобы эту характеристику получать из текущего состояния поля, по сути даешь внешнему коду возможность задавать ее какую угодно и когда угодно. По факту, то, будет ли возвращаться правильное или неправильное количество живых клеток model-field инстансом, у тебя вообще от внешнего кода зависит. Условно, ты где-то во внешнем коде можешь ошибиться, и model-field на запрос о количестве живых клеток будет возвращать какую-то дичь, и тебе придется сидеть колупаться во всех местах, где устанавливается количество живых клеток. Т.е. в общем случае, у тебя даже алгоритм того, каким образом будет количество живых клеток считаться не определен, тупо потому что это публичный метод и он может любым извращенным способом вызываться.

> Или процессорное время ничто, восприятие программиста все? Любые жертвы во имя красоты кода? 

Во-первых, как я говорил ранее, я не уверен, что твой вариант более оптимизирован. Во-вторых, главная задача данного этапа обучения (по моему мнению) - сделать так, чтобы стажеры научились лучше писать код, чем пишут перед ревью (читай, меньше быдлокодили).  Явно задача оптимизации здесь не стоит. Это не значит конечно, что стоит вообще ложить на все и кучу лишних операций делать и писать так, чтобы у тебя 5х5 поле лагало адски, но если заниматься оптимизацией, то она должна быть обоснована и выполнена грамотно, а не абы как. Короче говоря: первостепенно - читаемость, все остальное - потом.

Самая мякотка теперь: если ты внимательно читал пункт про сет методы, то мог заметить, что основная претензия именно к ним, а не к тому, что ты инкрементишь/декрементишь счетчик. То есть сам по себе подход с этим счетчиком имеет право на жизнь, но если ты его грамотно реализуешь, без сеттера. Управляя этим счетчиком как приватным полем строго в рамках класса model-field и предоставляя только геттер.

**Comment by Sergio-Ka** [comment]
Убрал этот функционал вообще ибо не нужен. Мертвое поле все равно вызовет остановку ибо это тоже устойчивая комбинация. Ввиду того, что механизм определения необходимости остановки будет переписан - не вижу смысла городить огород в этом конкретном случае.

**Comment by chmnkh** [comment]
Да, справедливо.
