### ISSUE TITLE
Очистка поля

### ISSUE THREAD

**Issue by chmnkh** [Sergio-Ka/GameOfLife#9]
```
    this.field = Array(this.ySizeOfField).fill(null);
    this.field.forEach((item, i) => {
      this.field[i] = Array(this.xSizeOfField).fill(null);
      this.field[i].forEach((itemInside, j) => {
        this.field[i][j] = new Cell();
      });
    });
```
На мой взгляд, намного логичней выглядит вариант, когда `clearField` очищает текущее поле, а не создает зачем-то новое и заполняет его какими-то значениями
т.е. строчки с `fill(null)` на самом деле лишние

**Comment by Sergio-Ka** [comment]
Исправил
